# Use helper image
image: 616966241685.dkr.ecr.eu-central-1.amazonaws.com/glue-cicd/glue-python:latest

# Stages
stages:
- init

# Environment variables
variables:
  GIT_SSL_NO_VERIFY: "true"
  PIPELINE_TYPE: "trunked"

  DOCKER_AUTH_CONFIG: |
    {
      "credHelpers": {
        "616966241685.dkr.ecr.eu-central-1.amazonaws.com": "ecr-login"
      }
    }

# JOBS
# ====================
# Fetch pipeline logic
fetch_logic:
  stage: init
  script:
    # insert gitlab-ci-token into $GIT_LOGIC_URL so we do not need credentials
    - export GIT_LOGIC_URL=$(echo -n "$(echo $GIT_LOGIC_URL | sed "s#://#://gitlab-ci-token:${CI_JOB_TOKEN}@#g")")
    # making sure to check it out into a dir called talend-artifact-builder, independent of actual TAB repo name
    - git clone -b master --depth 1 ${GIT_LOGIC_URL} lifecycle
    - cp -rf lifecycle/logic/* .
    - python lifecycle.py
  tags:
    - ci
    - global
    - aws-616966241685

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BEFORE_SHA == '0000000000000000000000000000000000000000' && $CI_PIPELINE_SOURCE != "web"
      when: never
    - when: always
